ALTER TABLE "FACSHOPDB"."PERSON_GROUPS" DROP CONSTRAINT FK_PERSON_GROUPS_PERSON
ALTER TABLE "FACSHOPDB"."PERSON_GROUPS" DROP CONSTRAINT FK_PERSON_GROUPS_GROUPS
ALTER TABLE "FACSHOPDB"."CUSTOMER_ORDER" DROP CONSTRAINT FK_CUSTOMER_ORDER_ORDER_STATUS1
ALTER TABLE "FACSHOPDB"."CUSTOMER_ORDER" DROP CONSTRAINT FK_CUSTOMER_ORDER_CUSTOMER1
ALTER TABLE "FACSHOPDB"."PRODUCT" DROP CONSTRAINT FK_PRODUCT_CATEGORY
ALTER TABLE "FACSHOPDB"."ORDER_DETAIL" DROP CONSTRAINT FK_ORDER_DETAIL_PRODUCT
ALTER TABLE "FACSHOPDB"."ORDER_DETAIL" DROP CONSTRAINT FK_ORDER_DETAIL_ORDER

DROP TABLE "FACSHOPDB"."PERSON_GROUPS"
DROP TABLE "FACSHOPDB"."PERSON"
DROP TABLE "FACSHOPDB"."GROUPS"
DROP TABLE "FACSHOPDB"."ORDER_DETAIL"
DROP TABLE "FACSHOPDB"."CUSTOMER_ORDER"
DROP TABLE "FACSHOPDB"."ORDER_STATUS"
DROP TABLE "FACSHOPDB"."PRODUCT"
DROP TABLE "FACSHOPDB"."CATEGORY"